name: receitas_do_chef
description: "Um aplicativo de receitas usando IA para gerar receitas a partir de fotos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # State Management
  provider: ^6.1.1

  # UI Components
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5

  # HTTP & API
  http: ^1.1.2

  # Utils
  path: ^1.8.3
  path_provider: ^2.1.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Descomente e adicione seus assets aqui
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - .env

  # Descomente e adicione suas fontes aqui
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700